name: 'Publish Docker Images'
description: 'Build and push Docker images'

inputs:
  version:
    required: true
  variant:
    required: true
  dockerhub_username:        # <— пробрасываем секреты как inputs
    required: true
  dockerhub_token:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - run: |
        chmod +x build-base-images.sh
        ./build-base-images.sh ${{ inputs.variant }}
      shell: bash

    - run: |
        chmod +x push-to-dockerhub.sh
        ./push-to-dockerhub.sh ${{ inputs.dockerhub_username }} ${{ inputs.version }} ${{ inputs.variant }}
      shell: bash
